### ISSUE TITLE
Viqo Mac環境でのバグについての報告

### ISSUE THREAD

**Issue by keyplayer4869** [diginatu/Viqo#24]
osバージョン：mac osx 10.10.2
viqoバージョン：2.0
発症状況：Viqoのログイン設定に下記の項目を設定してOKを押すと必ず落ちる
1.　ニコ生のユーザーデータのmailとPass入力
2.　ログイン方法のユーザーセッションのfirefox以外の方法選択(firefoxは持ってないので試していません)
3. 上の状況でokを押した場合落ちます。
4. 取得ボタンを押した場合でも落ちます

発症後：1. viqoを起動しても強制終了する。つまり起動できません。
            2. 発症後に Application Support の Viqo フォルダ削除するとViqo は起動するが発症　　　　状況と同じ状態になる。

**Comment by Nick-ANFiT** [comment]
keyplayer4869 さんの症状について再現するか試してみた。

OS X 10.10.3 上で ~/Application Support/Viqo フォルダを消した後に自分が放送主として自分のコミュニティで試してみたが、再現しなかった。
Safari 使用。ログイン方法は
1.「コメビュからログイン」＆取得のボタンを押しても押さなくても Viqo は異常終了しなかった。取得ボタンを押したかどうかに関係なく、その後「OK」を押しても VIqo は異常終了せず。
2.「直接入力」から「OK」を押しても Viqo は異常終了せず。
上記は報告。

下記は推測。
あくまでも非常にあてずっぽうな推測。
1. ディスクのアクセス権の修復（OS X 独特のシステム管理上の作業の1つ）をやると改善するかもしれない。（しないかもしれない）
2.自分は MacPorts で色々インストールしているので、それが影響してたりするのかしら？（全然関係ないかもしれないけど、普通な環境との相違点として思いついたので一応書いてみた）

lubuntu 環境で試そうと思ったら自分が使ってるの 32bit 版だったので実際に試すかどうかは未定。

**Comment by raccy** [comment]
報告ありがとうございます。

私の方でもfirefoxから取得以外の方法で何度も試したことがありますが、「OK」押下で落ちたことは一度もないです。
もしかしたら、私のはコンパイルした環境だからと言うのはあるかもしれません。
(環境依存はないようにバイナリ作っているはずなのですが…)
あとは私の環境も10.10.3ぐらいでしょうか、違いは。

他にちょっと考えられるのは、現在バイナリ配布しているバージョンでは、希に落ちる不具合があることです。
発生条件が環境依存(というより、メモリの状態依存)のため、状況によっては必ず発生する場合と、
発生しない場合があります。
最新のmasterブランチでは修正済みですので、そちらを試していただくことは可能でしょうか？
最新ソースからバイナリを作る方法は[パッケージ化方法](https://github.com/diginatu/Viqo/wiki/%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E5%8C%96%E6%96%B9%E6%B3%95)に載っています。
よくわからないというのであれば、プレリリースのバイナリを作成しますので、ご連絡下さい。

**Comment by Nick-ANFiT** [comment]
現時点での経過報告：
・Qt Creator でのビルドは成功するが、その次の macdeployqt コマンドでエラーがでる。
・この状態で viqo.dmg 内の viqo.app をアプリケーションフォルダにコピーして起動できるところまでは確認した。
・動作確認はまだやってない。

----

ビルドについての詳細：

ビルドしようとすると、途中で下記のメッセージが出力されます。

% ~/Qt5.4.1/5.4/clang_64/bin/macdeployqt viqo.app -dmg
ERROR: no file at "/opt/local/lib/mysql55/mysql/libmysqlclient.18.dylib"
ERROR: no file at "/usr/local/lib/libpq.5.dylib"

自分の環境では、libmysqlclient.18.dylib やファイル名に libmysqlclient を含むファイルは無いみたいです。
/usr/lib/libpq.5.dylib はあります。

ということで、MySQL 5.5.42 （MacPorts での 5.5 系列の最新版）をインストールしてみました。
libmysqlclient.18.dylib のエラーは消えた。
libpq の方のエラーはまだ出るので PostgreSQL 9.4.1 をインストール。
libpq のエラー変わらず。

ビルドフォルダの中には viqo.app と viqo.dmg はできていて、viqo.dmg を開くと viqo.app のアイコンが見えるところまでは確認しました。

現状ではここまでしかわからんけど、viqo.dmg 内の viqo.app をアプリケーションフォルダにコピーしてから起動すると起動はしたので後で試します。

とりあえず以上。

**Comment by raccy** [comment]
@Nick-ANFiT 確認ありがとうございます。

"/opt/local/lib/mysql55/mysql/libmysqlclient.18.dylib"のエラーは無視しても大丈夫です。
QtのDBモジュールでMySQLでアクセスするときだけ必要になるようです。
(ViqoではDBはSQLiteしか使用していません。)

"/usr/local/lib/libpq.5.dylib"側というか、こっちの方があとあと問題が出る時があります。
homebrewやmacportsでQtのライブラリをいれている場合だと、Qt本家のインストーラで
入れた方のQtライブラリ(デフォルトでは~/Qt/5.4/以下にある)を見に行かずにそっちを見に行っちゃう場合があります。
バージョンが違っている場合などは予期せぬエラーになる場合があるので注意してみて下さい。

macdeployqtは配付用にコンパイル環境の依存関係をなくすだけですので、
もし、そもそも正常に動作しないようであれば、macdeployqtを実行せずに、動作するか試してみて下さい。
なお、macdeployqtを一度でも実行している場合は、バイナリが作られたフォルダは
全部削除してから、ビルドしなおしてください。

**Comment by Nick-ANFiT** [comment]
バイナリが作成されたフォルダを一旦削除する必要があるという事で、やりなおしてみた。

まとめ：自分の環境では Viqo は落ちなかった。

----

自分の環境：
　OS X 10.10.3 + Safari 8.0.5 + CamTwist 3.0β、かんたん配信
　Qt 5.4.1、Qt Creator 3.3.1
　Viqo は 2015-05-06 10:05 JST 頃に git clone したのをビルドしたもの
　MySQL 5.5.42, PostgreSQL 9.4.1 （MacPorts でインストール）

----

確認手順詳細：

1. アカウント設定の Mail, Pass にニコ生のアカウントのメールアドレスとパスワードを入力する
　ログイン方法でブラウザを指定、Safari
　a. 取得ボタンを押さずに OK ボタン
　b. 取得ボタンを押して OK ボタン
　ここで Viqo 落ちず。
　Viqo を手動で終了後に Application Support  の Viqo フォルダ削除。

2.アカウント設定の Mail, Pass にニコ生のアカウントのメールアドレスとパスワードを入力する
　ログイン方法で直接入力、ユーザーセッションの項目は空欄のままでOKボタン
　Viqo 落ちず。
　Viqo を手動で終了後に Application Support  の Viqo フォルダ削除。

3.アカウント設定の Mail, Pass にニコ生のアカウントのメールアドレスとパスワードを入力する
　ログイン方法でコメビュからログイン
　a. 取得ボタンを押さないで OK を押す。
　b. 取得ボタンを押して OK を押す。
　Viqo 落ちず。
　Viqo を手動で終了後に Application Support  の Viqo フォルダ削除。

**Comment by raccy** [comment]
希に落ちる不具合を修正したバージョン2.1をリリースしましたので、お試し下さい。

リリース前のmasterブランチでは落ちないようなので、このIssueは一旦閉めます。
もし、2.1でも再度起きるようであれば、ご連絡下さい。

**Comment by tomedesu** [comment]
osバージョン：mac osx 10.11.6
viqoバージョン：2.3.3
同時に起動するソフト：OBS 0.15.1、LadioCast、InsomniaX
ネット環境：Y!mobile

上記の条件でViqoを使用してニコニコ生放送を行ったところ、『予期せぬエラー』が発生します。
毎回、１時間以内に発生していると思うのですが、使用目的が「ミラー放送の垂れ流し」なので、放置した状態でキープできないと困るのです。

対処の方、よろしくお願い申し上げます。

**Comment by tomedesu** [comment]
追記でございます。

使用ブラウザ：Safari 

不具合に気付いた時にはパソコンが熱を帯びており、かなり熱くなっていることが確認できます。
