### ISSUE TITLE
コメント受信時でインターフェイスフリーズ

### ISSUE THREAD

**Issue by henriquebremenkanp** [diginatu/Viqo#26]
コメント受信時のところに```say -v kyoko "%comment%"```入れてるんですけど、Sayコマンドが全部読み上げるまでインターフェイスがフリーズします。
読み終わってから「コメント」タブにコメントが現れます
長いコメントのときとか、コメントが多いときとかは結構時間待つんで、これは他のスレッドで発動できませんかな

OSXは10.10.3です

外人だから日本語がおかしかったらごめん。
手伝えることもあったら、ぜひ知らせてください

Viqo作ってくれてありがとう！毎日使ってるよ(*´ω｀*)ｂ

**Comment by diginatu** [comment]
バグ報告ありがとうございます。

報告いただいた問題は既知の問題で、読み上げの際、
スレッドを分けると同時に読み上げが起きてしまう
ということで一時的に今のような形で対応しています。

読み上げに関しては現在、[Riqo](https://github.com/diginatu/Riqo) という読み上げ援助ツールを
作成することで対応しようとしているところです。
（まだViqo側の対応ができていないので未完成）

それが完成すればコマンド実行は複数スレッドで実行するようにしても
いいかなと思っています。

コントリビュートは大歓迎ですので
ぜひ気軽にTwitter(@desineigh)などに一報くださればと思います。
