### ISSUE TITLE
MacOS10.10.4での異常終了について

### ISSUE THREAD

**Issue by obatans** [diginatu/Viqo#27]
【環境】
・Viqo Ver.2.0
・ Mac OSX 10.8.4（アクセス権修復済）

【症状】
ViqoをDL後、アカウント設定でMailとPASSを入力してOKを押すと異常終了し、
その後再度起動すると即異常終了となり起動できません。
（キャッシュの読み込みはできました。）

**Comment by diginatu** [comment]
Viqo 2.1で同じ状況になるか試してみてください。
（READMEの更新ができていないです。すみません。）

**Comment by obatans** [comment]
Viqo Ver2.1をDLして試しましたが異常終了しました。

参考になるかわかりませんが一連の挙動を録画しておきました。
https://www.youtube.com/watch?v=Vt6RGL1p-Sc

よろしくお願いします。

**Comment by diginatu** [comment]
難しいですね

もしかしたら2.1以前でできていた保存ファイルを消去するとうまく行くかもしれません

セーブデータの保存場所
https://github.com/diginatu/Viqo/wiki/%E3%82%BB%E3%83%BC%E3%83%96%E3%83%87%E3%83%BC%E3%82%BF

**Comment by obatans** [comment]
2.0、2.1共にAppCleanerにて完全に削除しています。

環境情報の記載ミスがありましたすみません。

Mac OSは10.10.4でした。
ちなみに別のMac OSX 10.10.1では正常に動作を確認しました。
10.10.4が原因なのでしょうか？

**Comment by raccy** [comment]
私の環境も10.10.4ですが、正常に動作しています。

動画を見させて貰いましたが、Google Chromeからの取得がおかしいかもしれません。
本来であれば、暗号化されている関係で、Google Chromeからセッション取得では
キーチェーンのダイアログが出てくるはずなのですが、それが出てきていないようです。
原因切り分けのために、「コメビュからログイン」や他ブラウザから取得でも
同じ現象が起きるかどうか試してみてくれませんか？

**Comment by obatans** [comment]
セッション取得に関して、他ブラウザとコメビュからのログインと動作を細分化して施行した結果以下のようになりました。

・メールアドレスとパスワードの入力のみでOKを押すと異常終了し、
　起動直後に異常終了するようになり実質起動できない

・メールアドレスとパスワード入力をせずにセッションを取得すると
　正常に取得でき、「メールとパスワードが入力できてません」のダイアログがでる。
　（異常終了はしない。）

**Comment by obatans** [comment]
MacをクリーンアップしてOSを再インストールして試行してみましたが結果は同じでした。

AppCleanerでの削除項目は下記の通りですが、データはこれで全てだと思うのですがまだ他に隠れているようであればご教授ください。
![2015-07-24 19 50 31](https://cloud.githubusercontent.com/assets/13298371/8873015/55af091e-323d-11e5-9e99-2eb12f3249f2.png)

**Comment by kiralin7566** [comment]
自分もOS X 10.10.5とViqo 2.3の組み合わせで同じ現象に悩まされています。
Safari、Firefox、Chromeのいずれを使っても、セッション情報を取得して初期設定をした瞬間に強制終了してしまい、それ以降二度と起動しません。
![2015-10-16 16 56 43](https://cloud.githubusercontent.com/assets/14978511/10536548/e7711826-7426-11e5-9c5f-34972b5ce112.png)

OS X 10.9の頃から一度も起動できたことがないのですが、何かよい解決方法はないでしょうか。

**Comment by diginatu** [comment]
スタックトレースを載せてくれていたので考えられるところだけ直して2.3.1のタグを切りました。
解決するとは限りませんが試してみてください。

**Comment by raccy** [comment]
OpenSSL関係のライブラリがうまくいってないかも知れません。
issues#29 でCommon Cryptoに変更する？らしいので、それをお持ちください。

**Comment by raccy** [comment]
OpenSSLからCommon Cryptoに変えたv2.3.2がリリースされました。Mac版のバイナリを用意していますので、現象が出ないか試してみてください。

**Comment by obatans** [comment]
Ver.2.3.2でも同様の現象が出るみたいです。

以下レポート内容をテキストファイルにコピーしたのを添付しておきます。
https://www.dropbox.com/s/m8a5zuayq0db062/viqo%E3%83%AC%E3%83%9D.txt?dl=0

**Comment by kiralin7566** [comment]
うちでも起動しなくなりました。

https://www.dropbox.com/s/ghmd4wkzp51nz7v/viqo_2015-10-25-193106_nagisa.txt?dl=0

**Comment by kiralin7566** [comment]
2.3.2のソースコードを自前でビルドしたら起動するようになりました。
どこがよかったのか、よく分かりません。

**Comment by kiralin7566** [comment]
自力でビルドしてみたら正常に起動しました。
ただ、Aboutを見るとバージョン情報が2.3.1のままだったりするので、正しくビルドできてるのかがよく分かりません。ソースは2.3.2のを拾ってきてるのですが…。

**Comment by diginatu** [comment]
アバウトの番号変えるの忘れました
ごめんなさい

見た所同じ症状のようですね
コンパイル時のlibcryptoのバージョンとかに依存している（？）

**Comment by kiralin7566** [comment]
私はOS X 10.10.5 + Xcode 7.1(7B91b)上でビルドしたものを使ったところ、問題なく起動できてコメントも拾えました。（枠取り等は試していません）

**Comment by diginatu** [comment]
原因が不明で現在でも問題があるのかも不明なため一旦閉じます。
問題が発生すれば新しいIssueを立ててください。
