### ISSUE TITLE
Qt 5.5.1 でコンパイルエラー

### ISSUE THREAD

**Issue by diginatu** [diginatu/Viqo#28]
発生環境
-------

+ ubuntu 14.04
+ Qt 5.5.0 / gcc

エラー例
---------

```
../Viqo/src/NicoLiveManager/nicookie.cpp:691:22: error: variable 'QDataStream stream' has initializer but incomplete type
   QDataStream stream(device.read(4));
                      ^
../Viqo/src/NicoLiveManager/nicookie.cpp:692:23: error: incomplete type 'QDataStream' used in nested name specifier
   stream.setByteOrder(QDataStream::BigEndian);
                       ^
```

**Comment by raccy** [comment]
Macでは普通にQt 5.5.0でコンパイルできました。(Mac版バイナリはQt 5.5.0でコンパイルしています)
ただ、clangで無効なオプションがデフォルトでついているらしく、その警告だけ出ます。
動作には今のところ問題ないようです。Linux版Qtの問題でしょうかね？

**Comment by diginatu** [comment]
手元の環境でClangでも試した所全く同じエラーでストップしました。
コンパイラによらないのでQtの問題か仕様変更だと思います
仕様どうりならちょっと様子を見ても良いかもしれませんね

**Comment by kiralin7566** [comment]
自分もGitで最新ソースを拾ってきて、同じ所で止まってしまいました。
環境もほぼ一緒（Linux Mint 17.2 / Qt 5.5.1）

**Comment by diginatu** [comment]
I fixed
https://github.com/diginatu/Viqo/commit/532dbda5de3f14ebe5cbc09a2fc0fec277d24e3b
