### ISSUE TITLE
Mac OS X 10.11 + Xcode 7 環境でopensslのヘッダが無いためコンパイルできない

### ISSUE THREAD

**Issue by raccy** [diginatu/Viqo#29]
MacではOpenSSLのサポートを打ち切る予定のため、
10.11では一足先にヘッダ類が削除されてしまったようです。
代わりに[Common Crypto](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/Common%20Crypto.3cc.html)を使う必要があります。

私の環境ではもうコンパイルできなくなったので、バイナリ版はしばらく無いです。
どうしてもバイナリが欲しいという要望があれば、Homebrewのopenssl依存版を作成します。

修正は、やっぱり俺？

**Comment by kiralin7566** [comment]
どちらにつけて良いのか分かりませんでしたが、一応こちらに。
OS X 10.10＋Xcode 7環境でコンパイルしましたが、OpenSSLのところでエラーになりバイナリを作れませんでした。

../Viqo-2.3.1/src/NicoLiveManager/nicookie.cpp:41:10: fatal error: 'openssl/aes.h' file not found
#include <openssl/aes.h>
         ^
1 error generated.
make: *** [nicookie.o] Error 1
15:45:30: プロセス "/usr/bin/make" はコード 2 で終了しました。
プロジェクト viqo のビルド・デプロイ中にエラーが発生しました (キット Desktop Qt 5.5.1 clang 64bit)
ステップ "Make" 実行中
15:45:30: 経過時間: 01:02

**Comment by raccy** [comment]
@kiralin7566 さん
うーん、どうやらXcode 7になってからopensslのヘッダがなくなったようです。前にコンパイルしたときは問題なかったんですが、あのときはOS X 10.10 + Xcode 6だったからかもしれません。

とりあえず、手元でコンパイルはできたのでやり方を書いておきます。

1. [Homebrew](http://brew.sh/index_ja.html)が入っていない人はインストールします。やり方はリンク先に載っています。

2. Homebrew版OpenSSLが入っていない人は、下記コマンドでOpenSSLを入れます。
    ```
    brew install openssl
    ```

3. Qt Creatorでプロジェクトを開いて、「viqo.pro」について下記編集を行います。
    1. 下記行を適当に追加します。
        ```
        INCLUDEPATH += /usr/local/opt/openssl/include
        ```

    2. 下記の部分を
        ```
        unix: LIBS += -lcrypto
        ```
        下記に修正します。
        ```
        unix: LIBS += -L/usr/local/opt/openssl/lib -lcrypto
        ```

4. あとはコンパイルするだけ。

**Comment by kiralin7566** [comment]
正常にコンパイルできて、異常終了することはなくなりました。
実際に全ての機能が使えるかはまだ試していません。

**Comment by raccy** [comment]
Fixed by #30
